# Copy the packages listed in stdlib/vendored.toml into stdlib/ and register them in stdlib/Manifest.toml.
# Usage: julia contrib/vendor_stdlibs.jl
using TOML
using Pkg: Versions

const ROOT = dirname(@__DIR__)
const STDLIB = joinpath(ROOT, "stdlib")

"""The fields of a stdlib's Project.toml that vendoring reads."""
struct Package
    uuid::String
    version::Union{Nothing, VersionNumber}
    deps::Vector{String}
    compat::Dict{String, String}
end

"""Parse `stdlib/<name>/Project.toml`."""
function read_package(name::AbstractString)::Package
    project = TOML.parsefile(joinpath(STDLIB, name, "Project.toml"))
    version = haskey(project, "version") ? VersionNumber(project["version"]) : nothing
    deps = sort!(String.(collect(keys(get(project, "deps", Dict{String, String}())))))
    compat = Dict{String, String}(get(project, "compat", Dict{String, String}()))
    return Package(project["uuid"], version, deps, compat)
end

"""An existing stdlib, from its stdlib/Manifest.toml entry."""
function manifest_package(entries::AbstractVector)::Package
    entry = only(entries)
    version = haskey(entry, "version") ? VersionNumber(entry["version"]) : nothing
    return Package(
        entry["uuid"],
        version,
        String.(get(entry, "deps", String[])),
        Dict{String, String}(),
    )
end

"""Highest `vX.Y.Z` tag of `repo`."""
function latest_release(repo::AbstractString)::String
    tags = [
        m[1]
        for m in eachmatch(
            r"refs/tags/(v\d+\.\d+\.\d+)$"m,
            read(`git ls-remote --tags $repo`, String),
        )
    ]
    if isempty(tags)
        error("no release tags in $repo")
    end
    return "v" * string(maximum(VersionNumber, tags))
end

"""Replace `stdlib/<name>` with `ref` of `repo`, without its git metadata."""
function vendor!(name::AbstractString, repo::AbstractString, ref::AbstractString)::Nothing
    tag = ref == "release" ? latest_release(repo) : ref
    dest = joinpath(STDLIB, name)
    rm(dest; recursive = true, force = true)
    run(`git clone -q --depth 1 --branch $tag $repo $dest`)
    for junk in (".git", ".github", "Manifest.toml")
        rm(joinpath(dest, junk); recursive = true, force = true)
    end
    println("$name ← $repo@$tag")
    return nothing
end

"""Make `stdlib/<name>` a symlink to the in-tree package at `path`, relative to stdlib/."""
function link!(name::AbstractString, path::AbstractString)::Nothing
    dest = joinpath(STDLIB, name)
    rm(dest; recursive = true, force = true)
    symlink(path, dest)
    println("$name → $path")
    return nothing
end

"""Fail unless each vendored package's deps are stdlibs whose versions its [compat] admits."""
function check(
    vendored::AbstractVector{<:AbstractString},
    packages::Dict{String, Package},
)::Nothing
    for name in vendored
        package = packages[name]
        for dep in package.deps
            if !haskey(packages, dep)
                error(
                    "$name depends on $dep, which is not a stdlib; add it to stdlib/vendored.toml",
                )
            end
        end
        for (dep, spec) in package.compat
            have = dep == "julia" ?
                VERSION :
                haskey(packages, dep) ? packages[dep].version : nothing
            if have !== nothing && !(have in Versions.semver_spec(spec))
                error("$name requires $dep $spec, but stdlib has $have")
            end
        end
    end
    return nothing
end

"""`table` as TOML text with sorted keys."""
function sorted_toml(table::AbstractDict)::String
    buffer = IOBuffer()
    TOML.print(buffer, table; sorted = true)
    return String(take!(buffer))
end

"""Add or replace the stdlib Project.toml and Manifest.toml entries of the vendored packages."""
function register!(
    vendored::AbstractVector{<:AbstractString},
    packages::Dict{String, Package},
)::Nothing
    project_path, manifest_path = joinpath(STDLIB, "Project.toml"),
        joinpath(STDLIB, "Manifest.toml")
    project, manifest = TOML.parsefile(project_path), TOML.parsefile(manifest_path)
    for name in vendored
        package = packages[name]
        project["deps"][name] = package.uuid
        manifest["deps"][name] = [Dict(
            "uuid" => package.uuid,
            "version" => string(package.version),
            "deps" => package.deps,
        )]
    end
    write(
        joinpath(STDLIB, "vendored.mk"),
        "# Generated by contrib/vendor_stdlibs.jl from stdlib/vendored.toml\nVENDORED_STDLIBS := ",
        join(vendored, ' '),
        '\n',
    )
    write(
        joinpath(STDLIB, ".gitattributes"),
        "# Generated by contrib/vendor_stdlibs.jl from stdlib/vendored.toml\n",
        join(("/$name/** linguist-vendored\n" for name in vendored)),
    )
    write(project_path, sorted_toml(project))
    write(
        manifest_path,
        "# This file is machine-generated - editing it directly is not advised\n\n",
        sorted_toml(manifest),
    )
    return nothing
end

function main()::Nothing
    sources = TOML.parsefile(joinpath(STDLIB, "vendored.toml"))
    for (name, source) in sources
        if haskey(source, "path")
            link!(name, source["path"])
        else
            vendor!(name, source["repo"], source["ref"])
        end
    end
    vendored = sort!(collect(keys(sources)))
    packages = Dict(
        name => manifest_package(entries)
        for (name, entries) in TOML.parsefile(joinpath(STDLIB, "Manifest.toml"))["deps"]
    )
    merge!(packages, Dict(name => read_package(name) for name in vendored))
    check(vendored, packages)
    register!(vendored, packages)
    return nothing
end

main()
