# Generated by contrib/vendor_stdlibs.jl from stdlib/vendored.toml
VENDORED_STDLIBS := CodeTracking Compiler Glob JuliaInterpreter LoweredCodeUtils OrderedCollections PackageCompiler Preferences RelocatableFolders Revise Scratch
